//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        public int Id { get; set; }
        public string FOLIO { get; set; }
        public string NOMBRES { get; set; }
        public string APELLIDOS { get; set; }
        public string DOMICILIO { get; set; }
        public string TELEFONO { get; set; }
        public string EMAIL { get; set; }
        public int NOTOMAS { get; set; }
        public System.DateTime FECHAALTA { get; set; }
        public System.DateTime FECHAMODIFICACION { get; set; }
        public int ENCARGADOSId { get; set; }
    }
}
